# Generated by Django 4.1.1 on 2022-09-26 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_announcement_blog_distirct_region_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region')),
            ],
            options={
                'verbose_name': 'Distirict',
                'verbose_name_plural': 'Distiricts',
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.district'),
        ),
        migrations.DeleteModel(
            name='Distirct',
        ),
    ]
